name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - requested

#on:
#  workflow_run:
#    workflows: [ "Build" ]
#    types:
#      - completed
#      - requested

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
